//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorDetail
    {
        public string DoctorID { get; set; }
        public string DoctorName { get; set; }
        public string Specaility { get; set; }
        public string IsAvailable { get; set; }
    }
}
