//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetail
    {
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string HealthConditions { get; set; }
    }
}
